In [1]:
from sklearn import datasets
from scipy.spatial import distance
import numpy as np

iris = datasets.load_iris()
X = iris.data

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


In [2]:
x1 = X[0,:]
x2 = X[1,:]

v = np.var(X, axis=0)

print(x1)
print(x2)
print(v)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[0.68112222 0.18871289 3.09550267 0.57713289]


In [7]:
def seuclideanScratch(p,q,v):
    return np.sqrt(np.sum(((p-q)**2 / v), axis=0))

seuclideanScratch(x1,x2,v)

1.1762186834130144

In [8]:
def seuclideanScipy(p,q,v):
    return distance.seuclidean(p,q,v)

seuclideanScipy(x1,x2,v)

1.1762186834130146

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]


In [10]:
x1 = X[0,:]
x2 = X[1,:]

v = np.var(X, axis=0)

print(x1)
print(x2)
print(v)

[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
[-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
[1. 1. 1. 1.]


In [11]:
seuclideanScratch(x1,x2,v)

1.1762186834130153

In [12]:
seuclideanScipy(x1,x2,v)

1.1762186834130153

In [13]:
print(distance.euclidean(x1,x2))
print(distance.seuclidean(x1,x2,v))

1.1762186834130146
1.1762186834130153


In [14]:
X = iris.data

x1 = X[0,:]
x2 = X[1,:]

S = np.cov(X.T, ddof=0)
S = np.identity(4)*S

print(x1)
print(x2)
print(S)

print(np.var(X, axis=0))

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[[ 0.68112222 -0.          0.          0.        ]
 [-0.          0.18871289 -0.         -0.        ]
 [ 0.         -0.          3.09550267  0.        ]
 [ 0.         -0.          0.          0.57713289]]
[0.68112222 0.18871289 3.09550267 0.57713289]


In [15]:
a = x1-x2
a

array([0.2, 0.5, 0. , 0. ])

In [16]:
r = np.matmul(a,np.linalg.inv(S))
r

array([0.29363306, 2.64952756, 0.        , 0.        ])

In [17]:
r3= np.matmul(r,np.transpose(a))
np.sqrt(r3)

1.1762186834130144

In [18]:
def seuclideanDot(p,q,V):
    V = np.linalg.inv(V)
    r = (p-q) @ V @ (p-q)
    return np.sqrt(r)

seuclideanDot(x1,x2,S)

1.1762186834130144

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]


In [20]:
x1 = X[0,:]
x2 = X[1,:]

S = np.cov(X.T, ddof=0)
S = np.identity(4)*S


print(x1)
print(x2)
print(S)

[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
[-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
[[ 1. -0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [21]:
seuclideanDot(x1,x2,S)

1.1762186834130153

In [22]:
print(seuclideanDot(x1,x2,np.identity(4)))
print(distance.seuclidean(x1,x2,np.diag(np.identity(4))))
print(distance.euclidean(x1,x2))

1.1762186834130146
1.1762186834130146
1.1762186834130146
